# -*- coding: utf-8 -*-
"""webpage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYWU00h_tHBUWPDLfyb1A4ioVv0atAEM
"""

!pip install pytesseract
!pip install gtts
!pip install gradio
!pip install easyocr
!pip install torch torchvision torchaudio

import cv2
import numpy as np
import easyocr
from gtts import gTTS
import os
import gradio as gr

# Initialize EasyOCR reader
reader = easyocr.Reader(['en'])

def segment_and_save_words(image):
    try:
        # Detect words using EasyOCR
        result = reader.readtext(image)
        recognized_text = []

        for detection in result:
            top_left = tuple([int(val) for val in detection[0][0]])
            bottom_right = tuple([int(val) for val in detection[0][2]])
            text = detection[1]
            font = cv2.FONT_HERSHEY_SIMPLEX
            image = cv2.rectangle(image, top_left, bottom_right, (0, 255, 0), 2)
            #image = cv2.putText(image, text, top_left, font, .5, (0, 0, 0), 2, cv2.LINE_AA)
            recognized_text.append(text)

        # Convert recognized text to audio
        audio_text = " ".join(recognized_text)
        audio_file = text_to_audio(audio_text)

        return image, audio_text, audio_file

    except Exception as e:
        print("An error occurred:", e)
        return None, None, None

def text_to_audio(text):
    try:
        # Generate audio from text using gTTS
        tts = gTTS(text=text, lang='en')
        tts.save('output.mp3')
        return "output.mp3"  # Return the file path of the generated audio
    except Exception as e:
        print("An error occurred:", e)

def play_audio(audio_file):
    try:
        os.system(f"mpg123 {audio_file}")  # Play the audio using mpg123 (replace with your preferred audio player)
    except Exception as e:
        print("An error occurred:", e)

# Gradio interface
image_input = gr.Image()
image_output = gr.Image()
text_output = gr.Textbox(label="Extracted Text")
submit_button = gr.Button("Submit")
audio_output = gr.Audio(label="Play Audio")


app = gr.Interface(
    fn=segment_and_save_words,
    inputs=image_input,
    outputs=[image_output, text_output, audio_output],
    title="Img-Txt-Speech",
    allow_flagging=False
)

def play_audio_wrapper(input_text):
    audio_file = text_to_audio(input_text)
    play_audio(audio_file)

app.launch()